version: '3.0'

services:
  db:
    image: postgres:11.1
  web:
    build: .
    command: >
      bash -c "pip install -r requirements.txt && 
      python manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db