# Generated by Django 2.1.3 on 2018-11-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='comment')),
                ('num_likes', models.IntegerField(verbose_name='comment likes')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50, verbose_name='Game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='tag_name')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(max_length=1000, verbose_name='post')),
                ('num_likes', models.IntegerField(verbose_name='post likes')),
                ('delay_time', models.BigIntegerField(verbose_name='delay time')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Game')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cms.Tag')),
            ],
        ),
    ]
