# Generated by Django 2.1.3 on 2018-11-13 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_comment_game_tag_tournamentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
